volumes:
  data:

services:
  app:
    build: .
    image: ghcr.io/rahn-it/wol-gui:master
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 8080
    volumes:
      - data:/app/db

  